### PR TITLE
Smooth plots using 1D filter

### PR DESCRIPTION
**Pull request by pstansell**
Hello @takuseno, here is the pull request for #37 (please check that it's okay as this is my first ever PR).

### CODE REVIEW

**Comment by pstansell** [comment]
Do I need to add `scipy==1.6.0` to `requirements.txt` to fix the import error from Linter?

**Review by takuseno — CHANGES_REQUESTED** [review]
Thank you for your contribution! Largely looks good to me! But, I'd like you to add `scipy` to `setup.py` too.
https://github.com/takuseno/d3rlpy/blob/dcdc25408a319bbef1f6b6f7be3b6d1b5a4097fa/setup.py#L62

**Review by takuseno — APPROVED** [review]

**Comment by takuseno** [comment]
@pstansell Thanks for the change! I'll merge this after the CI finishes.

**Comment by pstansell** [comment]
Thanks for accepting the change.  It's been a pleasure and a learning experience for me.

**Comment by pstansell** [comment]
I just pulled your recent changes to hopefully help your tests pass.

**Comment by takuseno** [comment]
Thanks for updating the branch. You don't have to care about the codecov status. If `test` and `format check` in GitHub Actions pass, I'll merge this.

**Pull request merged**
