### PR TITLE
correctly clear the remaining links of transitions when overwriting the replay buffer

### PR DESCRIPTION
**Pull request by gunshi**

### CODE REVIEW

**Comment by gunshi** [comment]
I added a callback so that every time we overwrite a transition, we make sure we clear the prev_transition property of the next transition in the list.

**Comment by takuseno** [comment]
@gunshi Thinking about this again. I think this is good to merge. Let me run tests.

**Comment by takuseno** [comment]
It seems that there is a format error. Could you try this to fix it? Thanks!
```
pip install black==22.3.0 mypy==0.942 pylint==2.13.5 yapf isort
./scripts/format
./scripts/lint
```

**Comment by gunshi** [comment]
Hey @takuseno,
I ran the above commands and got:

`[~/code/d3rlpy-1]$ ./scripts/format
+ [[ -z '' ]]
+ ISORT_ARG=
+ BLACK_ARG=
+ YAPF_ARG=-i
+ isort -l 80 --profile black d3rlpy tests

+ black -l 80 d3rlpy tests
All done! ✨ 🍰 ✨
199 files left unchanged.
+ yapf -r -vv -i examples reproductions
Reformatting examples/atari/train_bc.py
Reformatting examples/atari/train_cql.py
Reformatting examples/atari/train_dqn.py
Reformatting examples/cartpole/train_dqn.py
Reformatting examples/online/train_atari.py
Reformatting examples/online/train_discrete_sac.py
Reformatting examples/online/train_dqn.py
Reformatting examples/online/train_sac.py
Reformatting examples/ope/fqe_atari.py
Reformatting examples/ope/fqe_pybullet.py
Reformatting reproductions/extra/sac_online_dist.py
Reformatting reproductions/extra/sac_online_multistep.py
Reformatting reproductions/extra/td3_plus_bc_dist.py
Reformatting reproductions/extra/td3_plus_bc_multistep.py
Reformatting reproductions/finetuning/awac.py
Reformatting reproductions/finetuning/iql.py
Reformatting reproductions/offline/awac.py
Reformatting reproductions/offline/bcq.py
Reformatting reproductions/offline/bear.py
Reformatting reproductions/offline/combo.py
Reformatting reproductions/offline/cql.py
Reformatting reproductions/offline/crr.py
Reformatting reproductions/offline/discrete_bcq.py
Reformatting reproductions/offline/discrete_cql.py
Reformatting reproductions/offline/iql.py
Reformatting reproductions/offline/mopo.py
Reformatting reproductions/offline/nfq.py
Reformatting reproductions/offline/plas.py
Reformatting reproductions/offline/plas_with_perturbation.py
Reformatting reproductions/offline/qr_dqn.py
Reformatting reproductions/offline/sac.py
Reformatting reproductions/offline/td3.py
Reformatting reproductions/offline/td3_plus_bc.py
Reformatting reproductions/online/double_dqn.py
Reformatting reproductions/online/dqn.py
Reformatting reproductions/online/fqf.py
Reformatting reproductions/online/iqn.py
Reformatting reproductions/online/qr_dqn.py
Reformatting reproductions/online/sac.py`

`[~/code/d3rlpy-1]$ ./scripts/lint
+ mypy d3rlpy
d3rlpy/wrappers/sb3.py:10: error: Cannot find implementation or library stub for module named "stable_baselines3.common.buffers"
d3rlpy/wrappers/sb3.py:10: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 104 source files)`

There seem to be no changes to commit related to the files I edited if I understand this correctly?

**Comment by takuseno** [comment]
Hmm, `isort` seems complaining about import orders. Can you check `git diff`?
```
+ [[ -z true ]]
+ ISORT_ARG='--check --diff'
+ BLACK_ARG=--check
+ YAPF_ARG=-d
+ isort -l 80 --profile black --check --diff d3rlpy tests
ERROR: /home/runner/work/d3rlpy/d3rlpy/d3rlpy/online/buffers.py Imports are incorrectly sorted and/or formatted.
--- /home/runner/work/d3rlpy/d3rlpy/d3rlpy/online/buffers.py:before	2023-03-26 01:0[7](https://github.com/takuseno/d3rlpy/actions/runs/4407423358/jobs/7964239719?pr=269#step:7:8):54.722110
+++ /home/runner/work/d3rlpy/d3rlpy/d3rlpy/online/buffers.py:after	2023-03-26 01:09:26.530[8](https://github.com/takuseno/d3rlpy/actions/runs/4407423358/jobs/7964239719?pr=269#step:7:9)11
@@ -[10](https://github.com/takuseno/d3rlpy/actions/runs/4407423358/jobs/7964239719?pr=269#step:7:11),8 +10,8 @@
     MDPDataset,
     Transition,
     TransitionMiniBatch,
+    clear_prev,
     trace_back_and_clear,
-    clear_prev,
 )
 from .utility import get_action_size_from_env
```

**Comment by takuseno** [comment]
Feel free to reopen this if you have any further discussion. Please note that the nightly branch has been merged and the latest update `v2.0.2` has been released.

**Pull request closed without merging**
