### PR TITLE
Fix for 2D array and update tests to include this observation shape

### PR DESCRIPTION
**Pull request by emrul**
Attempt to fix for issue #264

### CODE REVIEW

**Comment by takuseno** [comment]
@emrul Thank you for your PR! Can you check the format error in CI?

**Comment by emrul** [comment]
I am without access to my dev env at the moment but next week I can - it's strange that it's complaining about that file, I added like 8 characters :-/

**Comment by takuseno** [comment]
You can simply run `./scripts/format` and commit the changes to fix this.

**Comment by emrul** [comment]
> ./scripts/format

I have a stupid question... when I run this command it reformats 33 files even though I only modified 2. I will look at what happened, maybe not using right config or something.

**Comment by emrul** [comment]
@takuseno - the 2 modified files pass the tests now. Thank you for your patience.

**Review by takuseno — APPROVED** [review]
LGTM. Thank you for your contribution!

**Pull request merged**
