### PR TITLE
bc: seperate loss into pieces

### PR DESCRIPTION
**Pull request by hasan-yaman**
Seperate loss of DiscreteBC into two pieces.

### CODE REVIEW

**Review by takuseno — COMMENTED** [review]
@hasan-yaman Hi, thanks for the PR! The change looks reasonable to me. Before merging this PR, can you delete this file?
`examples/debug.py`

**Comment by takuseno** [comment]
The error seen in `format check` seems caused by the new Gymnasium package. I've fixed this issue at the latest commit https://github.com/takuseno/d3rlpy/commit/b699b521d4759c2a4b35be29227777edf9f6c7f1 . Therefore, you can just ignore it in this PR.

**Comment by hasan-yaman** [comment]
Hi @takuseno thanks for the comments! Updated the PR.

**Review by takuseno — APPROVED** [review]
LGTM. Thank you for your contribution!

**Pull request merged**
